from __future__ import annotations

from datetime import UTC, datetime, timedelta

from app.api.routers.admin import generate_review_queue, review_action, review_audit
from app.schemas.review import ReviewActionRequest, ReviewCandidateInput
from app.services.review import ReviewCandidate, review_service


def _candidate(candidate_id: str, confidence: float, detected_at: datetime, severity: float, corridor_priority: int) -> ReviewCandidate:
    return ReviewCandidate(
        candidate_id=candidate_id,
        candidate_type="flood",
        corridor_id="indus-mid",
        district="Dadu",
        detected_at=detected_at,
        confidence=confidence,
        operational_severity=severity,
        corridor_priority=corridor_priority,
        exposure_significance=0.7,
        breach_suspicion=0.5,
        before_sar_url="s3://before",
        after_sar_url="s3://after",
        optical_support_url=None,
        baseline_overlay_url="s3://baseline",
        confidence_breakdown={"sar": 0.7},
        exposure_summary={"population": 1200},
        source_scene_references=["S1-A"],
        system_notes="auto",
    )


def test_review_queue_selects_and_ranks_candidates() -> None:
    service = review_service
    service._items.clear()  # noqa: SLF001
    service._audit_log.clear()  # noqa: SLF001
    now = datetime(2026, 1, 5, tzinfo=UTC)

    packets = service.generate_review_queue(
        [
            _candidate("low", 0.45, now - timedelta(hours=3), 0.9, 5),
            _candidate("high", 0.86, now - timedelta(hours=1), 0.95, 5),
            _candidate("medium", 0.62, now - timedelta(hours=8), 0.7, 4),
        ],
        now=now,
    )

    assert [packet.candidate.candidate_id for packet in packets] == ["high", "medium"]
    assert packets[0].review_score > packets[1].review_score


def test_review_actions_geometry_and_audit() -> None:
    service = review_service
    service._items.clear()  # noqa: SLF001
    service._audit_log.clear()  # noqa: SLF001
    now = datetime(2026, 1, 5, tzinfo=UTC)
    service.generate_review_queue([_candidate("c-1", 0.8, now - timedelta(hours=2), 0.9, 5)], now=now)

    service.apply_action(
        candidate_id="c-1",
        action="edit_geometry",
        actor="analyst-1",
        geometry={"type": "Polygon", "coordinates": []},
    )
    service.apply_action(candidate_id="c-1", action="change_class", actor="analyst-1", candidate_class="breach")
    service.apply_action(candidate_id="c-1", action="assign_confidence", actor="analyst-1", analyst_confidence=0.82)
    service.apply_action(candidate_id="c-1", action="accept", actor="analyst-1", notes="validated")
    state = service.apply_action(candidate_id="c-1", action="publish_alert", actor="analyst-1")

    assert state.status == "published"
    assert state.candidate_class == "breach"
    assert state.geometry is not None
    assert state.geometry.analyst_edited_geometry is not None
    assert state.geometry.final_published_geometry == state.geometry.analyst_edited_geometry
    audit = service.audit_records()
    assert len(audit) == 5
    assert audit[-1].old_status == "accepted"
    assert audit[-1].new_status == "published"


def test_admin_review_functions() -> None:
    review_service._items.clear()  # noqa: SLF001
    review_service._audit_log.clear()  # noqa: SLF001

    now = datetime(2026, 1, 7, 10, 0, tzinfo=UTC)
    queue_response = generate_review_queue(
        [
            ReviewCandidateInput(
                candidate_id="api-1",
                candidate_type="flood",
                corridor_id="indus-low",
                district="Sukkur",
                detected_at=now,
                confidence=0.74,
                operational_severity=0.81,
                corridor_priority=4,
                exposure_significance=0.67,
                breach_suspicion=0.43,
                before_sar_url="s3://before",
                after_sar_url="s3://after",
                optical_support_url="s3://optical",
                baseline_overlay_url="s3://baseline",
                confidence_breakdown={"sar": 0.72, "hydromet": 0.8},
                exposure_summary={"population": 3000},
                source_scene_references=["S1-A", "S1-B"],
                system_notes="generated by rules",
            )
        ]
    )
    assert queue_response[0]["candidate_id"] == "api-1"

    action_response = review_action(
        "api-1",
        ReviewActionRequest(action="accept", actor="analyst-a", notes="ok"),
    )
    assert action_response["status"] == "accepted"

    audit = review_audit()
    assert audit[-1]["new_status"] == "accepted"
