from datetime import UTC, datetime
import warnings

from fastapi.testclient import TestClient

with warnings.catch_warnings():
    warnings.simplefilter("ignore", DeprecationWarning)
    from app.api.main import app


def test_dashboard_view_and_map_layers() -> None:
    client = TestClient(app)

    view_response = client.get('/analytics/dashboard/views/Indus-Lower')
    assert view_response.status_code == 200
    payload = view_response.json()
    assert payload['corridor_id'] == 'Indus-Lower'
    assert payload['active_events'] >= 1
    assert payload['recent_events']

    events_layer = client.get('/analytics/map/events?corridor_id=Indus-Lower&simplify_tolerance=0.004')
    assert events_layer.status_code == 200
    layer_payload = events_layer.json()
    assert layer_payload['type'] == 'FeatureCollection'
    assert all(feature['properties']['corridor_id'] == 'Indus-Lower' for feature in layer_payload['features'])

    corridor_layer = client.get('/analytics/map/corridors?corridor_id=Indus-Lower')
    assert corridor_layer.status_code == 200
    assert corridor_layer.json()['features'][0]['id'] == 'Indus-Lower'


def test_review_dashboard_context_controls_and_filters() -> None:
    client = TestClient(app)
    now = datetime(2026, 1, 7, 10, 0, tzinfo=UTC)

    queue_response = client.post(
        '/admin/review/queue',
        json=[
            {
                'candidate_id': 'dash-1',
                'candidate_type': 'flood',
                'corridor_id': 'indus-low',
                'district': 'Sukkur',
                'detected_at': now.isoformat(),
                'confidence': 0.78,
                'operational_severity': 0.81,
                'corridor_priority': 4,
                'exposure_significance': 0.67,
                'breach_suspicion': 0.63,
                'before_sar_url': 's3://before',
                'after_sar_url': 's3://after',
                'optical_support_url': 's3://optical',
                'baseline_overlay_url': 's3://baseline',
                'confidence_breakdown': {'sar': 0.72, 'hydromet': 0.8},
                'exposure_summary': {'population': 3000},
                'source_scene_references': ['S1-A', 'S1-B'],
                'system_notes': 'generated by rules',
            }
        ],
    )
    assert queue_response.status_code == 200

    response = client.get('/analytics/dashboard/review?corridor_id=indus-low&confidence_band=high&breach_suspicion_min=0.5')
    assert response.status_code == 200
    payload = response.json()

    assert payload['layer_toggles']['previous_sar'] is True
    assert payload['layer_toggles']['anomaly_mask'] is True
    assert payload['action_controls']['accept_reject'] is True
    assert payload['action_controls']['publish_action'] is True
    assert payload['applied_filters']['corridor'] == 'indus-low'
    assert payload['queue_size'] >= 1
    assert payload['queue'][0]['context_links']['before_sar'] == 's3://before'


def test_snapshot_precompute_and_download() -> None:
    client = TestClient(app)

    precompute_response = client.post('/analytics/snapshots/precompute', json={'event_ids': ['evt-indus-001']})
    assert precompute_response.status_code == 200
    records = precompute_response.json()
    assert records[0]['event_id'] == 'evt-indus-001'

    snapshot_response = client.get('/analytics/snapshots/evt-indus-001')
    assert snapshot_response.status_code == 200
    assert snapshot_response.headers['content-type'] == 'image/png'
    assert snapshot_response.content.startswith(b'\x89PNG')
